FROM golang:1.10-alpine3.7
MAINTAINER YangJunhai <yangjunhai@xindong.com>
COPY . /go/src/github.com/pirateXD/registrator
RUN go build -ldflags "-X main.Version=$(grep "^version" /go/src/github.com/pirateXD/registrator/docker_run.config | awk -F'=' '{print $2}')" \
    -o /bin/registrator github.com/pirateXD/registrator && \
    rm -rf /go
ENTRYPOINT ["/bin/registrator"]
CMD ["--help"]